### ISSUE TITLE
Can't see fidelity

### ISSUE THREAD

**Issue by z3rO1997** [ccicconetti/netsquid#10]
I read the README.md and ran minimal.py.
The dependencies and unit tests did not raise any errors either.

However, I get the following output:
```
    degree-max = 4
    degree-min = 2
    degree-avg = 2.6666666666666665
    tsduration = 107965.09172722185
    sim_time = ['0.024']
```

The expected output from the README is as follows
```
  degree-max = 4
  degree-min = 2
  degree-avg = 2.6666666666666665
  tsduration = 107965.09172722185
  lenrate-1 = 7
  success-0.0 = 16
  success-0.6 = 16
  success-0.7 = 16
  success-0.8 = 16
  lenrate-3 = 6
  success-0.9 = 8
  lenrate-2 = 3
  meas = ['2.000', '2.000', '0.000', '1.000', '2.000', '0.000', '0.000', '2.000', '4.000', '2.000', '0.000', '1.000', '0.000', '1.000', '2.000', '2.000']
  fidelity-2 = ['0.867', '0.876', '0.868', '0.876', '0.876', '0.868', '0.868']
  delay = ['0.018', '0.018', '0.000', '0.117', '0.126', '0.108', '0.000', '0.234', '0.135', '0.234', '0.108', '0.009', '0.000', '0.009', '0.126', '0.018']
  latency-2 = ['0.018', '0.018', '0.018', '0.018', '0.018', '0.018', '0.018']
  length = ['5.379', '5.391', '1.790', '3.620', '5.392', '1.805', '1.797', '5.383', '8.962', '5.380', '1.783', '3.583', '1.800', '3.587', '5.358', '5.358']
  fidelity-0 = ['1.000', '1.000', '1.000', '0.999', '1.000']
  latency-0 = ['0.000', '0.000', '0.000', '0.000', '0.000']
  fidelity-1 = ['0.917', '0.926', '0.926']
  latency-1 = ['0.009', '0.009', '0.009']
  fidelity-4 = ['0.814']
  latency-4 = ['0.027']
  sim_time = ['0.208']
```

What's the problem?

**Comment by ccicconetti** [comment]
The simulator was developed with 0.9.8 version. I tried again with the latest available 1.1.7 and, as pointed out in the issue, the output is not produced. Btw, the old version is not available anymore in the pip registry ☹️ 

I did some quick debugging and some events are not generated but no exceptions are raised, very likely due to some changes in the default configuration parameters of some classes.

Unfortunately, I do not have time to address this with high priority, so I cannot make promises on _when_ this will be solved.

**Comment by z3rO1997** [comment]
I modified the run function inside swapprotocol.py as follows.

    def run(self):
        qports = [self._qmem.ports[port] for port in self._qmem.ports]
        qprog_exec = False
        qprog_path_id = None
        qprog_queue = []

        while True:
            # # Create an event triggered when ALL the memory ports
            # # receive a qubit: note that also lost qubits will trigger
            # # such an event notification
            in_qevent = None
            out_qevent = None

            for port in self._qmem.ports:
                if port in ["qin", "qout"]:
                    continue
                elif re.match(r'^qin\d+$', port):
                    if in_qevent is None:
                        in_qevent = self.await_port_input(self._qmem.ports[port])
                    else:
                        in_qevent &= self.await_port_input(self._qmem.ports[port])
                elif re.match(r'^qout\d+$', port):
                    if out_qevent is None:
                        out_qevent = self.await_port_input(self._qmem.ports[port])
                    else:
                        out_qevent &= self.await_port_input(self._qmem.ports[port])

            cevent = None
            for port in self._cport_names:
                if cevent is None:
                    cevent = self.await_port_input(self.node.ports[port])
                else:
                    cevent |= self.await_port_input(self.node.ports[port])

            # # Wait until any of the events happen
            if qprog_exec:
                expression = (
                    yield in_qevent | out_qevent
                        | cevent
                        | self.await_program(
                            self.node.qmemory, await_done=True, await_fail=True))
            else:
                expression = yield in_qevent | out_qevent | cevent

After the above modification, it works fine, but the result is different from the example.

Is the fix I made the right way?
I would like to know the opinion of the original author.
I'd like advice on what, if anything, is wrong with it.

**Comment by z3rO1997** [comment]
I'm writing again because I have an additional question I'd like to ask.

        while True:
            # # Create an event triggered when ALL the memory ports
            # # receive a qubit: note that also lost qubits will trigger
            # # such an event notification
            in_qevent = None
            out_qevent = None

            for port in self._qmem.ports:
                if port in ["qin", "qout"]:
                    continue
                elif re.match(r'^qin\d+$', port):
                    if in_qevent is None:
                        in_qevent = self.await_port_input(self._qmem.ports[port])
                    else:
                        in_qevent &= self.await_port_input(self._qmem.ports[port])
                elif re.match(r'^qout\d+$', port):
                    if out_qevent is None:
                        out_qevent = self.await_port_input(self._qmem.ports[port])
                    else:
                        out_qevent &= self.await_port_input(self._qmem.ports[port])

            cevent = None
            for port in self._cport_names:
                if cevent is None:
                    cevent = self.await_port_input(self.node.ports[port])
                else:
                    cevent |= self.await_port_input(self.node.ports[port])

            print(f"Waiting for in_qevent and out_qevent at time {time.time()}")

            if in_qevent is not None:
                in_expression = yield in_qevent
                print(f"in_qevent occurred at time {ns.sim_time():.1f}")

            if out_qevent is not None:
                out_expression = yield out_qevent
                print(f"out_qevent occurred at time {ns.sim_time():.1f}")

If you write it like above, you will only see results like "message received by qconn_0-1_PassThroughA_proto: Message(items=[Qubit('qsource_qconn_0-1-#1-0')]" or "in_qevent occurred at time".
If so, I assume that out_qevent is not occurring.
I suspected the connection part of qmemory's qout port, but couldn't confirm.

**Comment by ccicconetti** [comment]
I partially imported the patch in the branch `origin/netsquid-new-fixes`. It helps with making the simulation progress, but some problems remain. I will work on that. Any help will be appreciated :-)
